### PR TITLE
Minutes with link to retro board.

### PR DESCRIPTION
**Pull request by garloff**

### CODE REVIEW

**Comment by fkr** [comment]
I wondered wether we want to export the board (scruml.io offers to export it via json, csv and markdown) and attach it, so that we don't rely on the board staying around?

**Comment by fkr** [comment]
I added a change, I added an MD export of the board to the minutes file.
**however** I redacted the names of the authors of the items and also re-configured the scruml board to **not** display the names anymore.

**Review by fkr — APPROVED** [review]
LGTM

**Comment by garloff** [comment]
> 



> I added a change, I added an MD export of the board to the minutes file. **however** I redacted the names of the authors of the items and also re-configured the scruml board to **not** display the names anymore.

Very good improvements, thanks for performing them!

**Pull request merged**
