### PR TITLE
Feat/add community call 20240818.md

### PR DESCRIPTION
**Pull request by scoopex**

### CODE REVIEW

**Comment by FriederikeZelke** [comment]
Hey, the minutes are from 20240718, I don´t know how to change the file name... Otherwise I would do.

**Review by mbuechse — COMMENTED** [review]
Friederike already mentioned it: the file name is wrong (it must be July instead of August).

~~Also, and more importantly, my notes regarding SIG Std/Cert are gone!!! Can someone please revive them?~~

Sorry, my mistake. Those notes were from 2024-07-25 (whereas this PR is about the week before), and these notes are still here: https://input.scs.community/2024-scs-community-call?both#

**Comment by mbuechse** [comment]
I'm afraid the new file also needs renaming from Aug to Jul ;-)

**Review by mbuechse — APPROVED** [review]
Now this was very confusing. The new file was added and then (by the miracle of a merge) removed again. It took me a while to realize that the new file had already been merged in a separate PR! I used an interactive git rebase to clean up the commit history. Now it could be presented to any reviewers... but I will approve right away, so no more reviewing this thing...

**Pull request merged**
