### PR TITLE
Add the minutes of the sig-community from 2022-08-24

### PR DESCRIPTION
**Pull request by matfechner**
Signed-off-by: Mathias Fechner <fechner@osism.tech>

### CODE REVIEW

**Comment by fkr** [comment]
Set assignee to @ra-beer and @tibeer since they can judge, wether the minutes are complete.

**Review by tibeer — APPROVED** [review]
LGTM!

**Review by ra-beer — APPROVED** [review]
LGTM

**Comment by fkr** [comment]
thanks @tibeer @ra-beer

**Pull request merged**
