### PR TITLE
Add hackathon minutes for table documentation

### PR DESCRIPTION
**Pull request by maxwolfs**
Signed-off-by: maxwolfs <mail@maxwolfs.com>

### CODE REVIEW

**Comment by itrich** [comment]
As discussed, I guess that a symlink within the SIG Documentation subdirectory will help to find the results again in the future.

**Review by tibeer — APPROVED** [review]
Looks good!

**Comment by ra-beer** [comment]
LGTM. @maxwolfs: Thanks for the great teamwork at the hackathon :)

**Comment by maxwolfs** [comment]
> LGTM. @maxwolfs: Thanks for the great teamwork at the hackathon :)

Thanks too! :)

**Pull request merged**
