### PR TITLE
Minutes everywhere!

### PR DESCRIPTION
**Pull request by horazont**

### CODE REVIEW

**Review by garloff — APPROVED** [review]
/lgtm.
Thanks, Jonas!

**Comment by garloff** [comment]
Hi @horazont , I can not merge this, as your branch needs a merge from main before to avoid being outdated.
I can not do this merge into the cloudandheat:community-call branch as I lack the privileges to do so.
Will you do this? Or do you want to grant privileges to me?
THANKS!

**Comment by horazont** [comment]
Can we remove that requirement? I don't like pointless rebases and it will only create latencies because I look at github notifications really rarely.

**Comment by itrich** [comment]
> Can we remove that requirement? I don't like pointless rebases and it will only create latencies because I look at github notifications really rarely.

I guess that you need to check "Allow modifications by maintainers" within the pull request in this case.

**Review by fkr — APPROVED** [review]
LGTM

**Comment by fkr** [comment]
I will update the minutes once merged to include links to the other minutes (where they're now available)

**Comment by horazont** [comment]
@itrich I cannot do that, because the base repository is in the C&H org, and you can only allow that for non-org repositories for some stupid github reasons.

**Comment by itrich** [comment]
> @itrich I cannot do that, because the base repository is in the C&H org, and you can only allow that for non-org base repositories for some github reasons.

Sigh :disappointed: 
Could you though rebase onto main so that we can merge this PR? You can safely create branches in the future within our SCS Org as you have writing permissions.

**Comment by fkr** [comment]
Indeed. Pushing to a branch within the SCS-repo and do a PR from there solves this imho nicely.

**Comment by horazont** [comment]
I can do that, but we really should have a high-bandwidth chat about this requirement…

**Review by itrich — APPROVED** [review]

**Pull request merged**
